### ISSUE TITLE
Heroku compatibility

### ISSUE THREAD

**Issue by dguido** [llimllib/slask#16]
It's a bad practice to store keys in source control and Heroku typically recommends (via the 12factor guidelines) to store them and other application configuration in environment variables. I modified the config.py to contain the following as a result:

```
import os
config = {
   "token": os.environ.get('TOKEN'),
```

**Comment by llimllib** [comment]
yes, they probably should be in env vars; PR welcome.

(Although I prefer config files myself!)

**Comment by dguido** [comment]
derr I will figure this git thing out one day. For now, check it out here. Super simple:
https://github.com/dguido/slask/compare/llimllib:master...master

**Comment by llimllib** [comment]
All config is now done via environment variables in 946ec65343d97f1d3147aea9baa1b5a33562a377

**Comment by dguido** [comment]
Thanks!
